// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeter.proto

package greeter

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GreeterRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreeterRequest) Reset()         { *m = GreeterRequest{} }
func (m *GreeterRequest) String() string { return proto.CompactTextString(m) }
func (*GreeterRequest) ProtoMessage()    {}
func (*GreeterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{0}
}

func (m *GreeterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreeterRequest.Unmarshal(m, b)
}
func (m *GreeterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreeterRequest.Marshal(b, m, deterministic)
}
func (m *GreeterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreeterRequest.Merge(m, src)
}
func (m *GreeterRequest) XXX_Size() int {
	return xxx_messageInfo_GreeterRequest.Size(m)
}
func (m *GreeterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreeterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreeterRequest proto.InternalMessageInfo

func (m *GreeterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GreeterResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreeterResponse) Reset()         { *m = GreeterResponse{} }
func (m *GreeterResponse) String() string { return proto.CompactTextString(m) }
func (*GreeterResponse) ProtoMessage()    {}
func (*GreeterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{1}
}

func (m *GreeterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreeterResponse.Unmarshal(m, b)
}
func (m *GreeterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreeterResponse.Marshal(b, m, deterministic)
}
func (m *GreeterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreeterResponse.Merge(m, src)
}
func (m *GreeterResponse) XXX_Size() int {
	return xxx_messageInfo_GreeterResponse.Size(m)
}
func (m *GreeterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreeterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreeterResponse proto.InternalMessageInfo

func (m *GreeterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GreeterRequest)(nil), "greeter.GreeterRequest")
	proto.RegisterType((*GreeterResponse)(nil), "greeter.GreeterResponse")
}

func init() { proto.RegisterFile("greeter.proto", fileDescriptor_e585294ab3f34af5) }

var fileDescriptor_e585294ab3f34af5 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2f, 0x4a, 0x4d,
	0x2d, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x54, 0xb8,
	0xf8, 0xdc, 0x21, 0xcc, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e, 0x16, 0xbf,
	0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x49, 0x9b, 0x8b, 0x1f,
	0xae, 0xaa, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x82, 0x8b, 0xdd, 0x37, 0xb5, 0xb8, 0x38,
	0x31, 0x1d, 0xa6, 0x12, 0xc6, 0x35, 0xf2, 0xe5, 0x62, 0x87, 0x2a, 0x16, 0x72, 0xe2, 0xe2, 0x76,
	0x4f, 0x2d, 0x01, 0xf3, 0x32, 0xf3, 0xd2, 0x85, 0xc4, 0xf5, 0x60, 0xae, 0x40, 0xb5, 0x53, 0x4a,
	0x02, 0x53, 0x02, 0x62, 0x8d, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0xc5, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x41, 0x9e, 0xb5, 0x63, 0xc2, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	GetGreeting(ctx context.Context, in *GreeterRequest, opts ...grpc.CallOption) (*GreeterResponse, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) GetGreeting(ctx context.Context, in *GreeterRequest, opts ...grpc.CallOption) (*GreeterResponse, error) {
	out := new(GreeterResponse)
	err := c.cc.Invoke(ctx, "/greeter.Greeter/GetGreeting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	GetGreeting(context.Context, *GreeterRequest) (*GreeterResponse, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) GetGreeting(ctx context.Context, req *GreeterRequest) (*GreeterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGreeting not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_GetGreeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreeterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetGreeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greeter.Greeter/GetGreeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetGreeting(ctx, req.(*GreeterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greeter.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGreeting",
			Handler:    _Greeter_GetGreeting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greeter.proto",
}
